### Test Endpoint
GET http://localhost:3000/test

### Read File Endpoint
GET http://localhost:3000/file

### Write to File Endpoint
POST http://localhost:3000/file
Content-Type: application/json

{
  "content": "New content written from API!\nThis replaces the old content.\nTimestamp: 2026-02-25"
}

### Get All Users
GET http://localhost:3000/users

### Search Users by Name
GET http://localhost:3000/users?name=john

### Get Single User (ID: 1)
GET http://localhost:3000/users/1

### Get Single User (ID: 2)
GET http://localhost:3000/users/2

### Create New User - Bob
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Bob",
  "age": 35
}

### Create New User - Alice
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Alice",
  "age": 28
}

### Update User (ID: 1) - Full Update
PUT http://localhost:3000/users/1
Content-Type: application/json

{ "id": 1,
  "name": "Updated John",
  "age": 40
}

### Update User (ID: 2) - Partial Update (Age Only)
PUT http://localhost:3000/users/2
Content-Type: application/json

{ "id": 2,
  "name": "Updated jane",
  "age": 48
}

### Delete User (ID: 1)
DELETE http://localhost:3000/users/1

### Delete User (ID: 2)
DELETE http://localhost:3000/users/2